title: "Grégori – Profissional em Cibersegurança"
description: "Analista de Segurança da Informação | Especialista em SOC e Defesa Cibernética"
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
